GET http://localhost:3030/api/v1/anime/test
###
GET http://localhost:3030/api/v1/anime/oregairu
###
POST http://localhost:3030/api/v1/anime/
Content-Type: application/json

{
    "uri": "https://gogoanime.io/category/oregairu"
}
###
POST http://localhost:3030/api/v1/anime/episode/1
Content-Type: application/json

{
    "uri": "https://gogoanime.io/category/oregairu"
}
###
GET http://localhost:3030/api/v1/anime/
###
GET http://localhost:3030/api/v1/anime/popular/fetch