export const GET_TRENDING_ANIME = 'get-trending-anime'
export const GET_RECENT_ANIME = 'get-recent-anime'
export const GET_POPULAR_ANIME = 'get-popular-anime'
export const GET_ANIME_DETAILS = 'get-anime-details'
export const GET_EPISODE_DATA = 'get-episode-data'
export const GET_ALL_EPISODES = 'get-all-episodes'